elifesciences/api-dummy

src/bootstrap.php

Match no_empty_statement fixer

---

composer.lock
data/articles/04395.json
data/articles/05770.json
data/articles/09560.json
data/articles/10627.json
data/articles/13410.json
data/articles/14107.json
data/articles/16412.json
data/articles/16846.json
data/collections/tropical-disease.json
data/podcast-episodes/1.json
data/podcast-episodes/2.json
data/podcast-episodes/3.json
data/podcast-episodes/4.json
src/bootstrap.php

Add article authors

---

composer.lock
data/blog-articles/345983.json
data/collections/tropical-disease.json
data/experiments/1.json
data/experiments/2.json
data/experiments/3.json
data/experiments/4.json
data/experiments/5.json
src/bootstrap.php
src/validate.php

Also tidies up escaping of slashes.

Use FakeHttpsMessageValidator when testing

---

src/bootstrap.php
test/SmokeTest.php

To allow at least 7 items to make for 2 journal pages, returns all interviews and labs-experiments available

Barebones community content

---

src/bootstrap.php

`jdesrosiers/silex-cors-provider` currently turns all route-not-found 404s into a 405.

Add recommendations route

---

data/articles/15278.json

I cannot find out which API produced this data, so I am correcting the dimensions in place, looking at the info.json files. Grepping for `"width": 1$` does not give other results

These images should not have size 1

---

data/articles/09560.json

Useful for testing recommendations in ci

Add an external related article

---

composer.lock
data/collections/tropical-disease.json
data/people/bcooper.json
data/people/djones.json
data/people/fbloggs.json
data/people/jpublic.json
data/people/jqpublic.json
data/people/pjha.json
data/podcast-episodes/1.json
data/podcast-episodes/2.json
data/podcast-episodes/3.json
test/SmokeTest.php

- Removing subjects from podcast episodes
- Updating person type with composite type field
- Improved error message on validation

Updating with latest api-raml

---

data/recommendations/article-16412.json

I only added related articles so far

Adding recommendations sample

---

pin.sh

Useful in situation like search--ci and recommendations--ci, where the project can be pinned to a commit for a repeatable build
See also https://github.com/elifesciences/api-dummy-formula/pull/3

Script for pinning

---

data/blog-articles/359325.json

Useful for https://github.com/elifesciences/search/pull/158.

Add a list with blocks and strings

---

composer.json
composer.lock

Forgot to fix before merging #114.

Fix elife/content-negotiator constraint

---

data/articles/26231.json
src/bootstrap.php
test/SilexTestCase.php
test/SmokeTest.php

Makes https://github.com/elifesciences/search/pull/179 fail.

Article 26231 breaks in v2

---

composer.lock
data/annotations/jcarberry.json

Not bothering with a BC layer as it's optional.

Rename annotation parents to ancestors

---

Dockerfile.composer

Follows https://github.com/elifesciences/annotations/pull/85.

Improve Composer install

---

composer.lock
data/collections/tropical-disease.json
data/highlights/magazine.json
src/bootstrap.php
test/SmokeTest.php

Improves: elifesciences/issues#4294

Digests events support in lists

---

composer.lock
data/people/jpublic.json

Improves: https://github.com/elifesciences/elife-xpub/issues/545
Depends on: https://github.com/elifesciences/api-raml/pull/231

Add optional givenNames, surname and emailAddresses to person

---

data/highlights/announcements.json
data/highlights/community.json

Improves: https://github.com/elifesciences/issues/issues/4405

Highlights for community and announcements

---

composer.lock
src/bootstrap.php

Refs https://github.com/elifesciences/issues/issues/4766.

Add review articles

---

data/bioprotocols/article-15278.json
src/bootstrap.php
test/SmokeTest.php

https://github.com/elifesciences/issues/issues/4931

Add bioprotocols

---

src/bootstrap.php

Addressing this change which was done automatically as part of the promotional collections PR: https://github.com/elifesciences/api-dummy/pull/157/files#r404190970

Small cs fix

---

composer.json
composer.lock
data/blog-articles/378207.json
data/collections/tropical-disease.json
data/events/3.json
data/interviews/1.json
data/labs/80000003.json
data/podcast-episodes/3.json
data/promotional-collections/highlights-japan.json
data/subjects/biochemistry.json
src/bootstrap.php
test/SmokeTest.php

Introduce examples of social media images in doi and magazine content.

Social image complete

---

composer.json
composer.lock
src/validate.php

Remove a legacy dependancy that was breaking support for composer v2.
This resolves elifesciences/issues#6243

fix: remove mindplay/composer-locator dependancy

---

composer.json
composer.lock
data/covers/event-3.json
data/covers/press-package-425250.json
data/covers/reviewed-preprint-29561.json
src/bootstrap.php
test/SmokeTest.php

- reviewed-preprint
- event
- press-package

Add examples of new content to covers

---

data/labs/80000003.json

Re issue https://github.com/elifesciences/issues/issues/8585
Changed `jats4r.org` to `jats4r.niso.org`. I added a `/` to the end of the URL too, which is hopefully alright.

Update JATS4R url in json example.
